### ISSUE TITLE
Wire call issue for ESP32 platform

### ISSUE THREAD

**Issue by mjdonders** [Starmbi/hp_BH1750#10]
Thanks for the great work with this library.
For me it didn't work, and I'm guessing that this is based on the fact that I'm using an ESP32, and that Wire implementation is slightly different.
I think that based on the beginTransmission, requestFrom does not work in readValue.
After updating that to the following, it worked like a charm.
(main change: removed the beginTransmission/endTransmission, since that's not needed in the requestFrom/read construction)

unsigned int hp_BH1750::readValue()
{
  const byte bytesRequested = 2;
  byte buff[bytesRequested];

  unsigned int req = _wire->requestFrom((int)_address, (int)bytesRequested); // request two bytes
  if ((req == 0) || (req > bytesRequested))
  {
    _time = 999;
    _value = 0;
    return _value; // Sensor not found or other problem
  }

  unsigned int bytesRead=0;
  while(bytesRead<req) {
    if (_wire->available()) {
      buff[bytesRead] = _wire->read(); // Receive one byte
      bytesRead++;
    }
  }

  _nReads++; // Inc the physically count of reads
  _value = ((buff[0] << 8) | buff[1]);
 
  unsigned long mil = millis();
  if (_value > 0 && _time == 0)
    _time = mil - _startMillis; // Conversion time
  if (mil >= (_timeoutMillis) && (_time == 0))
    _time = mil - _startMillis;
  return _value;
}

**Comment by Starmbi** [comment]
Hello,

this issue was already solved:
https://github.com/Starmbi/hp_BH1750/pull/4/files
You can download the fixed library at 
https://github.com/Starmbi/hp_BH1750/releases/tag/1.0.1

Hope this helps.

**Comment by mjdonders** [comment]
Hello and thanks for the quick reply.
I do now see that it's fixed, but if i uninstall the library and re-install it again using the Arduino (2.0.3) IDE it downloads the incorrect older version again.
Do you maybe need a library.properties file update for this to work?
(not sure what's needed for this to work using the Arduino IDE)
Thanks!

Martijn.

**Comment by mjdonders** [comment]
I just noticed that you fixed it.
Thanks!

**Comment by Starmbi** [comment]
Thanks for your information!
