### ISSUE TITLE
esp32 S2 just halts

### ISSUE THREAD

**Issue by tablatronix** [Starmbi/hp_BH1750#3]
For some reason I cannot get this to work on the S2, ill keep testing and see if I can gather any debug or crash data.

my serial out put just stops, so not sure what to do here..

This line is where my code just stops..
`  unsigned int req = _wire->requestFrom((int)_address, (int)2); // request two bytes`

Any ideas welcome, pretty sure it worked on esp32, gonna test again, also all other i2c sensors work fine

**Comment by Starmbi** [comment]
It seems that no command for a request was sent. Please use a example code and check the wiring again.
Perhaps there is a issue with the S2. I don't know this device. Sorry.

**Comment by ladyada** [comment]
@tablatronix please try this fix
https://github.com/Starmbi/hp_BH1750/pull/4/files

**Comment by tablatronix** [comment]
Seems to be working now, closing
